name: ss58
description: Provides encoding and decoding methods for parsing substrate SS58 addresses.
version: 2.0.1
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/ss58
repository: https://github.com/leonardocustodio/polkadart
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  equatable: ^2.0.8 # MIT
  base_x: ^2.0.1 # MIT
  convert: ^3.1.2 # BSD-3-Clause
  cryptography: ^2.9.0 # Apache-2.0
  json_annotation: ^4.10.0 # BSD-3-Clause

dev_dependencies:
  lints: 6.1.0
  test: 1.29.0
  build_runner: ^2.11.1
  json_serializable: ^6.11.4

